<?php

namespace Julien\ParcInformatiqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogicielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogicielRepository extends EntityRepository
{
}
