<?php

namespace Julien\ParcInformatiqueBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SalleController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Julien\ParcInformatiqueBundle\Controller\SalleController();
        return $instance;
    }
}
