parcInfo_accueil:
    pattern:   /
    defaults:  { _controller: JulienParcInformatiqueBundle:ParcInfo:index }
#------------------------ voir entité
parcInfo_voir_salle:
    pattern:   /salle/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Salle:voir }

parcInfo_voir_logiciel:
    pattern:   /logiciel/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Logiciel:voir }

parcInfo_voir_reference:
    pattern:   /reference/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Reference:voir }
 
parcInfo_voir_ordi:
    pattern:   /ordi/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Ordi:voir}
    
parcInfo_voir_package:
    pattern:   /package/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Package:voir}
    
parcInfo_voir_OS:
    pattern:   /OS/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:OS:voir}
    
parcInfo_voir_peripherique:
    pattern:   /peripherique/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Peripherique:voir}
#------------------------ voir liste d'entité
parcInfo_voir_liste_salle:
    pattern:   /listeSalle/{page}
    defaults:  { _controller: JulienParcInformatiqueBundle:Salle:voirListe, page: 1  }
    
parcInfo_voir_liste_ordi:
    pattern:   /listeOrdi/
    defaults:  { _controller: JulienParcInformatiqueBundle:Ordi:voirListe }

parcInfo_voir_liste_OS:
    pattern:   /listeOS/
    defaults:  { _controller: JulienParcInformatiqueBundle:OS:voirListe }

parcInfo_voir_liste_logiciel:
    pattern:   /listeLogiciel/
    defaults:  { _controller: JulienParcInformatiqueBundle:Logiciel:voirListe }

parcInfo_voir_liste_peripherique:
    pattern:   /listePeripherique/
    defaults:  { _controller: JulienParcInformatiqueBundle:Peripherique:voirListe }

parcInfo_voir_liste_package:
    pattern:   /listepackage/
    defaults:  { _controller: JulienParcInformatiqueBundle:Package:voirListe }
#------------------------ ajouter entité
parcInfo_ajouter_salle:
    pattern:   /ajouter_salle
    defaults:  { _controller: JulienParcInformatiqueBundle:Salle:ajouter}

parcInfo_ajouter_reference:
    pattern:   /ajouter_reference
    defaults:  { _controller: JulienParcInformatiqueBundle:Reference:ajouter}

parcInfo_ajouter_ordi:
    pattern:   /ajouter_ordi
    defaults:  { _controller: JulienParcInformatiqueBundle:Ordi:ajouter}

parcInfo_ajouter_package:
    pattern:   /ajouter_package
    defaults:  { _controller: JulienParcInformatiqueBundle:Package:ajouter}

parcInfo_ajouter_logiciel:
    pattern:   /ajouter_logiciel
    defaults:  { _controller: JulienParcInformatiqueBundle:Logiciel:ajouter}

parcInfo_ajouter_OS:
    pattern:   /ajouter_OS
    defaults:  { _controller: JulienParcInformatiqueBundle:OS:ajouter}
    
parcInfo_ajouter_peripherique:
    pattern:   /ajouter_peripherique
    defaults:  { _controller: JulienParcInformatiqueBundle:Peripherique:ajouter}
#------------------------ modifier entité    
parcInfo_modifier_salle:
    pattern:   /modifier_salle/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Salle:modifier}

parcInfo_modifier_ordi:
    pattern:   /modifier_ordi/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Ordi:modifier}

parcInfo_modifier_reference:
    pattern:   /ajouter_reference
    defaults:  { _controller: JulienParcInformatiqueBundle:Reference:modifier}
      
parcInfo_modifier_package:
    pattern:   /modifier_package/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Package:modifier}
    
parcInfo_modifier_peripherique:
    pattern:   /modifier_peripherique/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Peripherique:modifier}

parcInfo_modifier_OS:
    pattern:   /modifier_OS/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:OS:modifier}

parcInfo_modifier_logiciel:
    pattern:   /modifier_logiciel/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Logiciel:modifier}
#------------------------ supprimer entité
parcInfo_supprimer_salle:
    pattern:   /supprimer_salle/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Salle:supprimer}

parcInfo_supprimer_ordi:
    pattern:   /supprimer_ordi/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Ordi:supprimer}

parcInfo_supprimer_OS:
    pattern:   /supprimer_os/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:OS:supprimer}

parcInfo_supprimer_reference:
    pattern:   /supprimer_reference/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Reference:supprimer}

parcInfo_supprimer_package:
    pattern:   /supprimer_package/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Package:supprimer}

parcInfo_supprimer_peripherique:
    pattern:   /supprimer_peripherique/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Peripherique:supprimer}
    
parcInfo_supprimer_logiciel:
    pattern:   /supprimer_logiciel/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Logiciel:supprimer}