parcInfo_accueil:
    pattern:   /
    defaults:  { _controller: JulienParcInformatiqueBundle:ParcInfo:index }
#------------------------ voir entité
parcInfo_voir_salle:
    pattern:   /salle/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Salle:voir }

parcInfo_voir_reference:
    pattern:   /reference/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Reference:voir }
 
parcInfo_voir_ordi:
    pattern:   /ordi/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Ordi:voir}
    
parcInfo_voir_package:
    pattern:   /package/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Package:voir}
    
parcInfo_voir_OS:
    pattern:   /OS/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:OS:voir}
#------------------------ voir liste d'entité
parcInfo_voir_liste_salle:
    pattern:   /listeSalle/
    defaults:  { _controller: JulienParcInformatiqueBundle:Salle:voirListe }
    
parcInfo_voir_liste_ordi:
    pattern:   /listeOrdi/
    defaults:  { _controller: JulienParcInformatiqueBundle:Ordi:voirListe }
    
parcInfo_voir_liste_package:
    pattern:   /listepackage/
    defaults:  { _controller: JulienParcInformatiqueBundle:Package:voirListe }
#------------------------ ajouter entité
parcInfo_ajouter_salle:
    pattern:   /ajouter_salle
    defaults:  { _controller: JulienParcInformatiqueBundle:Salle:ajouter}

parcInfo_ajouter_reference:
    pattern:   /ajouter_reference
    defaults:  { _controller: JulienParcInformatiqueBundle:Reference:ajouter}

parcInfo_ajouter_ordi:
    pattern:   /ajouter_ordi
    defaults:  { _controller: JulienParcInformatiqueBundle:Ordi:ajouter}

parcInfo_ajouter_package:
    pattern:   /ajouter_package
    defaults:  { _controller: JulienParcInformatiqueBundle:Package:ajouter}

parcInfo_ajouter_OS:
    pattern:   /ajouter_OS
    defaults:  { _controller: JulienParcInformatiqueBundle:OS:ajouter}
#------------------------ modifier entité    
parcInfo_modifier_salle:
    pattern:   /modifier_salle/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Salle:modifier}

parcInfo_modifier_ordi:
    pattern:   /modifier_ordi/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Ordi:modifier}

parcInfo_modifier_reference:
    pattern:   /ajouter_reference
    defaults:  { _controller: JulienParcInformatiqueBundle:Reference:modifier}
      
parcInfo_modifier_package:
    pattern:   /modifier_package/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Package:modifier}
#------------------------ supprimer entité
parcInfo_supprimer_salle:
    pattern:   /supprimer_salle/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Salle:supprimer}

parcInfo_supprimer_ordi:
    pattern:   /supprimer_ordi/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Ordi:supprimer}

parcInfo_supprimer_reference:
    pattern:   /supprimer_reference/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Reference:supprimer}

parcInfo_supprimer_package:
    pattern:   /supprimer_package/{id}
    defaults:  { _controller: JulienParcInformatiqueBundle:Package:supprimer}
