parameters:
#    julien_parc_informatique.example.class: Julien\ParcInformatiqueBundle\Example

services:
#    julien_parc_informatique.example:
#        class: %julien_parc_informatique.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
